version: "3"

services:
  coeiroink:
    image: kuwacom/coeiroink:gpu-COEIROINK-2.5.1
    ports:
      - "8080:80"
    volumes:
      - ./speaker_info:/app/speaker_info

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    restart: always
